-- Create tables for Devil's Deal Website

-- 1. Site Config (Single row expected, but table structure)
CREATE TABLE site_config (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  logo_url TEXT,
  about_text TEXT,
  banner_images TEXT[], -- Array of strings
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Banner Images (Deprecated - moved to site_config)
-- CREATE TABLE banner_images (
--   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   url TEXT NOT NULL,
--   created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
-- );

-- 3. Shows (Agenda)
CREATE TABLE shows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date DATE NOT NULL,
  time TIME NOT NULL,
  venue TEXT NOT NULL,
  address TEXT NOT NULL,
  ticket_links TEXT[], -- Array of strings
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Members
CREATE TABLE members (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  role TEXT NOT NULL,
  description TEXT,
  instagram TEXT,
  photos TEXT[], -- Array of strings
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 5. Products (Merchandise)
CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  price NUMERIC NOT NULL,
  images TEXT[], -- Array of strings
  colors TEXT[], -- Array of strings
  sizes TEXT[], -- Array of strings
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Insert initial config row
INSERT INTO site_config (logo_url, about_text) VALUES ('', '<p>Sobre a banda...</p>');

-- 6. Albums
CREATE TABLE albums (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  cover_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 7. Photos
CREATE TABLE photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  album_id BIGINT REFERENCES albums(id) ON DELETE CASCADE,
  url TEXT NOT NULL,
  order_index INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);


-- 8. Songs (Repertoire)
CREATE TABLE songs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 9. Storage Bucket for Images
INSERT INTO storage.buckets (id, name, public) VALUES ('images', 'images', true);

-- Policies for Storage (Allow public read, and public insert/update/delete for demo purposes)
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'images' );
CREATE POLICY "Public Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'images' );
CREATE POLICY "Public Update" ON storage.objects FOR UPDATE USING ( bucket_id = 'images' );
CREATE POLICY "Public Delete" ON storage.objects FOR DELETE USING ( bucket_id = 'images' );

