-- 10. Technical Rider
CREATE TABLE technical_rider (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  quantity INTEGER DEFAULT 1,
  minimum INTEGER DEFAULT 1,
  alternative TEXT,
  observations TEXT,
  photos TEXT[], -- Array of strings (URLs)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Add stage_map_url to site_config
ALTER TABLE site_config ADD COLUMN stage_map_url TEXT;

-- Policy for Technical Rider (Public Read, Public Write for demo)
ALTER TABLE technical_rider ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public Access Rider" ON technical_rider FOR SELECT USING ( true );
CREATE POLICY "Public Insert Rider" ON technical_rider FOR INSERT WITH CHECK ( true );
CREATE POLICY "Public Update Rider" ON technical_rider FOR UPDATE USING ( true );
CREATE POLICY "Public Delete Rider" ON technical_rider FOR DELETE USING ( true );
